config/routes.rb
Rails.application.routes.draw do

  # 顧客用ルーティング
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    get '/' => "homes#top", as: "root"
    get 'about' => 'homes#about'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdrawal'
      end
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      post :confirm, on: :collection
      get :complete, on: :collection
    end

    resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    get 'search' => 'searches#search'

  end



  # 管理者用ルーティング
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    #homes
    root to: "homes#top"
    #items
    resources :items,only: [:new,:index,:edit,:show,:update,:create]
    #genres
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    #customers
    resources :customers, only: [:index, :show, :edit, :update]
    #orders
    resources :orders, only: [:show, :update, :index]
    #order_items
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy #中間テーブル
  has_many :order_items, dependent: :destroy

  validates :name, presence: true
  validates :explanation, presence: true
  validates :tax_out_price, presence: true
  validates :is_sale, inclusion: [true, false]

  # [tax_out_price]に対して1.10を掛けた値を四捨五入して返す
  # [add_tax]の部分が重要なので消してはいけない[消費税コード]と検索すれば出てくる
  def add_tax_tax_out_price
      (self.tax_out_price * 1.10).round
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize: "#{width}x#{height}^", gravity: "center", crop: "#{width}x#{height}+0+0").processed
  end

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin! #ログイン済みの管理者のみに権限を与える

  def index #商品一覧
    @items = Item.page(params[:page]) #Item.page(params[:page])は現在のページ番号を表す
  end                                 #ペジネーションされた状態の情報を[@items]に格納する

  def new #商品新規登録表示
    @item = Item.new
  end

  def create #商品情報新規登録
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を新規登録しました。"
      redirect_to admin_item_path(@item) #商品詳細showへ遷移
    else
      render :new #失敗時は新規登録画面へ遷移
    end
  end

  def show #商品詳細
    @item = Item.find(params[:id])
  end

  def edit #商品編集
    @item = Item.find(params[:id])
  end

  def update #商品情報更新
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to admin_item_path(@item) #商品詳細showへ遷移
    else
      render :edit #失敗時は商品編集画面へ遷移
    end
  end

  private

  def item_params             #商品画像、商品名、商品説明、ジャンル、税抜価格、販売ステータス
    params.require(:item).permit(:image,:name,:explanation,:genre_id,:tax_out_price,:is_sale)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-4 md-2">
    <div class="col-md-6 mx-auto">
      <%= render 'admin/genres/error',obj: @item %>
      <h3 class="table col-3 label-background-color text-center border-bottom border-dark">商品編集</h3>
     <%= form_with model: @item,url: admin_item_path(@item.id) do |f| %>
      <table class="table table-borderless mt-3">
        <tbody>
          <tr>
            <td><%= f.label "商品画像" %></td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label "商品名" %></td>
            <td><%= f.text_field :name, class: "form-control", :placeholder => "商品名" %></td>
          </tr>
          <tr>
            <td><%= f.label "商品説明" %></td>
            <td><%= f.text_area :explanation, class: "form-control", :placeholder => "ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <td><%= f.label "ジャンル" %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "--選択してください--" %></td>
          </tr>
          <tr>
            <td><%= f.label '税抜価格' %></td>
            <td>
              <div class="input-group">
                <%= f.text_field :tax_out_price, class: 'form-control' %>
                <span>円</span>
              </div>
            </td>
          </tr>
          <tr>
            <td><%= f.label "販売ステータス" %></td>
            <td>
              <%= f.radio_button :is_sale, true %>
                <%= f.label :is_sale, '販売中' %>
              <%= f.radio_button :is_sale, false %>
                <%= f.label :is_sale, '販売停止中' %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <div class="mb-5 mx-auto">
          <%= f.submit "変更を保存", class:'btn btn-success' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container my-5" >
  <div class="row">
    <div class="col-3 mb-3 offset-1">
      <h3><strong class="border-bottom border-dark">商品一覧</strong></h3>
    </div>
      <div class="col-7 mb-3 text-right">
        <%= link_to new_admin_item_path, class: "text-decoration-none h2" do %>
    　    <i class="fas fa-plus-circle fa-lg" style="color: #d0d1d2;"></i>
    　  <% end %>
      </div>
    <div class="container mb-5">
      <div class="row">
        <div class="col-10 mx-auto">
        <table class="table table-hover text-center contents-area">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @items.each do |item| %>
          <tbody>
            <tr>
              <td class="py-4"><%= item.id %></td>
              <td class="py-4">
                <%= link_to admin_item_path(item.id) do %>
                <%= item.name %>
                <% end %>
              </td>
              <td class="py-4">¥<%= item.tax_out_price.to_s(:delimited) %></td>
              <td class="py-4"><%= item.genre.name %></td>
              <td class="py-4">
                <% if item.is_sale == false %>
                  <strong class="text-secondary">販売停止中<strong>
                <% else %>
                  <strong class="text-success">販売中</strong>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
         </table>
         <div class="pagination justify-content-center mt-3">
           <%= paginate @items, theme: 'bootstrap-5' %>
         </div>
        </div>
    　</div>
    </div>
　</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row mt-4 md-2">
    <div class="col-md-6 mx-auto">
      <%= render 'admin/genres/error',obj: @item %>
      <h3><span class="border-bottom border-dark">商品新規登録</span></h3>
    <%= form_with model: @item, url: admin_items_path do |f| %>
      <table class="table table-borderless mt-3">
        <tbody>
          <tr>
            <td><%= f.label "商品画像" %></td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label "商品名" %></td>
            <td><%= f.text_field :name, class: "form-control", :placeholder => "商品名" %></td>
          </tr>
          <tr>
            <td><%= f.label "商品説明" %></td>
            <td><%= f.text_area :explanation, class: "form-control", :placeholder => "ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <td><%= f.label "ジャンル" %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "--選択してください--" %></td>
          </tr>
          <tr>
            <td><%= f.label '税抜価格' %></td>
            <td>
              <div class="input-group">
                <%= f.text_field :tax_out_price, class: 'form-control' %>
                <span>円</span>
              </div>
            </td>
          </tr>
          <tr>
          <td><%= f.label "販売ステータス" %></td>
            <td>
              <%= f.radio_button :is_sale, true %>
                <%= f.label :is_sale, '販売中' %>
              <%= f.radio_button :is_sale, false %>
                <%= f.label :is_sale, '販売停止中' %>
            </td>
          </tr>
        </tbody>
      </table>
        <div class="row">
          <div class="mb-5 mx-auto">
            <%= f.submit "新規登録", class:'btn btn-lg btn-success' %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container my-5">
  <div class="row mt-4 md-2">
    <div class="col-md-10 mx-auto">
      <%= flash[:notice] %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-md-5">
      <div class="mx-5">
        <%= image_tag @item.get_image(350, 250) %>
      </div>
    </div>
    <div class="col-md-7" style="text-left">
      <h3><span class="border-bottom border-dark">商品詳細</span></h3>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th style="width: 30%">商品名</th>
            <td style="width: 70%"><%= @item.name %></td>
          </tr>
          <tr>
            <th style="width: 30%">商品説明 </th>
            <td style="width: 70%"><%= @item.explanation %></td>
          </tr>
          <tr>
            <th style="width: 30%">ジャンル</th>
            <td style="width: 70%"><%= @item.genre.name %></td>
          </tr>
          <tr>
            <th style="width: 30%"> 税込価格(税抜価格)</th>
            <td style="width: 70%"><%= @item.add_tax_tax_out_price.to_s(:delimited) %>（<%= @item.tax_out_price.to_s(:delimited) %>）円</td>
          </tr>
          <tr>
            <th style="width: 30%">販売ステータス</th>
            <td style="width: 70%">
              <% if @item.is_sale == false %>
                <strong class="text-secondary">販売停止中</strong>
               <% else %>
                <strong class="text-success">販売中</strong>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="my-5 ml-3">
        <%= link_to "編集する", edit_admin_item_path(@item.id),class: "btn btn-lg btn-success" %>
        <%= link_to "商品を追加する", new_admin_item_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>