config/routes.rb
Rails.application.routes.draw do

  # 顧客用ルーティング
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    get '/' => "homes#top", as: "root"
    get 'about' => 'homes#about'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdrawal'
      end
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      post :confirm, on: :collection
      get :complete, on: :collection
    end

    resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    get 'search' => 'searches#search'

  end



  # 管理者用ルーティング
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    #homes
    root to: "homes#top"
    #items
    resources :items,only: [:new,:index,:edit,:show,:update,:create]
    #genres
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    #customers
    resources :customers, only: [:index, :show, :edit, :update]
    #orders
    resources :orders, only: [:show, :update, :index]
    #order_items
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :delivery_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Deviseが提供する認証機能を有効にするために必要なメソッド
  # database_authenticatableは、ユーザーがパスワードを入力して認証するための機能
  # registerableは、ユーザーがアカウントを作成できるようにする機能
  # recoverableは、ユーザーがパスワードをリセットできるようにする機能
  # rememberableは、ユーザーのログイン情報を覚えておく機能
  # validatableは、ユーザーが入力した情報が正しいかどうかを検証する機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin! # ログイン済管理者のみにアクセスを許可する

  def index #顧客一覧
    @customers = Customer.page(params[:page]) #CustomerでCustomerモデルのデータを保持
  end                                         #[.page]メソッドでデータをペジネーションするために使用
                                              #(params[:page])で現在のページ番号を示すために使用されるパラメーター
  def show #顧客詳細
    @customer = Customer.find(params[:id])
  end

  def edit #顧客情報編集
    @customer = Customer.find(params[:id])
  end

  def update #顧客情報更新
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報の編集が完了しました。"
      redirect_to admin_customer_path(@customer.id) #編集成功時はshow(会員詳細)へ遷移
    else
      render :edit #編集に失敗した場合は編集画面へ遷移
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :is_deleted,:email)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_error.html.erb
<% if customer.errors.any? %>
  <h4><strong><%= customer.errors.count %>件のエラーが発生しました</strong></h4>
    <ul>
      <% customer.errors.full_messages.each do |message| %>
        <h5><li><%= message %></li></h5>
      <% end %>
    </ul>
<% end %>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-4 md-2">
    <div class="col-md-10 mx-auto">
      <%= render "error", customer: @customer %>
      <h3 class="text-center mb-3"><strong class="border-bottom border-dark">会員情報編集</strong></h3>
      <%= form_with model: @customer, url:admin_customer_path, method: :patch do |f| %>
        <div class="contents-area mb-3 pt-3">
          <div class="row mb-2 field">
            <div class="col-2 offset-md-1">会員ID</div>
            <div class="col-1"></div>
            <div class="col-1 pr-0"><%= @customer.id %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-2 offset-md-1"><%= f.label "お名前" %></div>
            <div class="col-1 text-right pr-0"><%= f.label "(姓)" %></div>
            <div class="col-1"><%= f.text_field :last_name, :size => "10" %></div>
            <div class="col-1 text-right pr-0"><%= f.label "(名)" %></div>
            <div class="col-1"><%= f.text_field :first_name, :size => "10" %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-2 offset-md-1"><%= f.label "フリガナ" %></div>
            <div class="col-1 text-right pr-0"><%= f.label "(セイ)" %></div>
            <div class="col-1"><%= f.text_field :last_name_kana, :size => "10" %></div>
            <div class="col-1 text-right pr-0"><%= f.label "(メイ)" %></div>
            <div class="col-1"><%= f.text_field :first_name_kana, :size => "10" %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-3 offset-md-1"><%= f.label "メールアドレス" %></div>
            <div class="col-3"><%= f.email_field :email, :size => "50" %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-3 offset-md-1"><%= f.label "郵便番号(ハイフンなし)" %></div>
            <div class="col-3"><%= f.text_field :post_code, :size => "10" %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-3 offset-md-1"><%= f.label "住所" %></div>
            <div class="col-3"><%= f.text_field :address, :size => "50" %></div>
          </div>

          <div class="row mb-2 field">
            <div class="col-3 offset-md-1"><%= f.label "電話番号(ハイフンなし)" %></div>
            <div class="col-3"><%= f.text_field :phone_number %></div>
          </div>

          <div class="row">
            <div class="col-3 offset-md-1">会員ステータス</div>
            <%= form_with model: @customer, url:admin_customer_path, method: :patch do |f| %>
              <div class="col-3">
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, '有効', class: "mr-2" %>
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, '退会' %>
              </div>
            <% end %>
          </div>

          <div class="row">
            <div class="col-2 offset-md-1"></div>
            <div class="col-2 offset-md-1 mt-3 mb-5">
              <%= f.submit "変更を保存", class:"  btn btn-success" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5" >
  <div class="row">
    <div class="col-3 mb-3 offset-1">
      <h3><strong class="border-bottom border-dark">会員一覧</strong></h3>
    </div>

      <div class="container mb-5">
        <div class="row">
          <div class="col-10 mx-auto">
            <table class="table table-hover text-center contents-area">
              <thead>
                <tr>
                  <th>会員ID</th>
                  <th>氏名</th>
                  <th>メールアドレス</th>
                  <th>ステータス</th>
                </tr>
              </thead>
              <% @customers.each do |customer| %>
              <tbody>
                <tr>
                <td class="py-4"><%= customer.id %></td>
                <td class="py-4">
                  <div class="link-secondary">
                    <%= link_to admin_customer_path(customer.id) do %>
                      <%= customer.last_name %><%= customer.first_name %>
                    <% end %>
                  </div>
                </td>
                <td class="py-4"><%= customer.email %></td>
                <td class="py-4">
                  <% if customer.is_deleted == false %>
                    <strong class="text-success">有効</strong>
                  <% elsif %>
                    <strong class="text-secondary">退会</stropng>
                  <% end %>
                </td>
                </tr>
              </tbody>
              <% end %>
            </table>
            <div class="pagination justify-content-center mt-3">
              <%= paginate @customers, theme: 'bootstrap-5' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class="container my-5" >
  <div class="row">
    <div class="col-4 mb-3 offset-1">
      <%= flash[:notice] %>
      <h3><strong class="border-bottom border-dark"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</strong></h3>
    </div>
      <div class="container mb-5">
        <div class="row">
          <div class="col-10 mx-auto">
            <table class="table table-borderless contents-area">
              <thead>
                <tr>
                  <th>会員ID</th>
                  <td><%= @customer.id %></td>
                </tr>
                <tr>
                  <th>氏名</th>
                  <td><%= @customer.last_name %><%= @customer.first_name %></td>
                </tr>
                <tr>
                  <th>フリガナ</th>
                  <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
                </tr>
                <tr>
                  <th>郵便番号</th>
                  <td><%= @customer.post_code %></td>
                </tr>
                <tr>
                  <th>住所</th>
                  <td><%= @customer.address %></td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td><%= @customer.phone_number %></td>
                </tr>
                <tr>
                  <th>メールアドレス</th>
                  <td><%= @customer.email %></td>
                </tr>
                <tr>
                  <th>会員ステータス</th>
                  <% if @customer.is_deleted == false %>
                    <td><strong><p class="text-success">有効</p></strong></td>
                  <% elsif %>
                    <td><strong><p class="text-secondary">退会</p></strong></td>
                  <% end %>
                </tr>
              </thead>
            </table>
          <div class="d-grid gap-2 d-md-block">
            <%= link_to edit_admin_customer_path(@customer.id), class: 'text-light' do %>
              <button class="btn btn-success" type="submit">編集する</button>
            <% end %>
            <%= link_to admin_orders_path, class: 'text-light' do %>
              <button class="btn btn-primary" type="submit">注文履歴一覧を見る</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>