config/routes.rb
Rails.application.routes.draw do

  # 顧客用ルーティング
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    get '/' => "homes#top", as: "root"
    get 'about' => 'homes#about'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdrawal'
      end
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      post :confirm, on: :collection
      get :complete, on: :collection
    end

    resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    get 'search' => 'searches#search'

  end



  # 管理者用ルーティング
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    #homes
    root to: "homes#top"
    #items
    resources :items,only: [:new,:index,:edit,:show,:update,:create]
    #genres
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    #customers
    resources :customers, only: [:index, :show, :edit, :update]
    #orders
    resources :orders, only: [:show, :update, :index]
    #order_items
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :items, through: :order_items #注文には商品が多くある
  has_many :order_items, dependent: :destroy #中間テーブル

  # enum(列拳型)で検索すれば使用方法が出てくる
  enum pay_method: { credit_card:0, transfer:1 }
  # 0=入金待ち、1=入金確認、2=製作中、3=発送準備中、4=発送済み
  enum status: { waiting:0, confirm:1, making:2, preparation:3, sent:4 }

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin! #ログイン済みの管理者のみ権限を与える

  def index #注文履歴一覧
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end

  def show #注文履歴詳細画面(ステータス編集を兼ねる)
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order.id)
  end

  def update #注文ステータス・着手状況の更新
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order.id)
    @order.update(order_params)

    if @order.status == Order.statuses.key(1)
      @order_items = OrderItem.where(params[:order_id])
      @order_items.each do |order_item|
        order_item.making_status = OrderItem.making_statuses.key(1)
        order_item.save
      end
    end
      redirect_to request.referer
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-3 mb-3 offset-1">
      <h3><strong class="border-bottom border-dark">注文履歴一覧</strong></h3>
    </div>

      <div class="container mb-5">
        <div class="row">
          <div class="col-10 mx-auto">
            <table class="table table-hover contents-area text-center">
              <thead>
                <tr class="text-center">
                  <th>購入日時</th>
                  <th>購入者</th>
                  <th>注文個数</th>
                  <th>注文ステータス</th>
                </tr>
              </thead>
              <tbody>
                <% @orders.each do |order| %>
                  <tr class="text-center">
                    <td class="py-4">
                      <%= link_to admin_order_path(order.id), method: :get do %>
                        <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                      <% end %>
                    </td>
                    <td class="py-4"><%= order.customer.last_name %><%= order.customer.first_name %></td>
                    <td class="py-4">
                      <% sum = 0 %>
                      <% order.order_items.each do |order_item| %>
                        <% sum += order_item.quantity %>
                      <% end %>
                      <%= sum  %>
                    </td>
                    <td class="py-4"><%= order.status_i18n %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="pagination justify-content-center mt-3">
            <%= paginate @orders, theme: 'bootstrap-5' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<!--注文履歴詳細-->
<div class="container my-4">
  <h2 class="pb-3 border-bottom border-dark"><strong>注文履歴詳細</strong></h2>
  <table class="table table-hover table-borderless">
    <tr class="row">
      <th class="h5 font-weight-bold">購入者</th>
      <td>
        <%= @order.customer.last_name %><%= @order.customer.first_name %>
      </td>
    </tr>

    <tr class="row">
      <th class="h5 font-weight-bold">注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>

    <tr class="row">
      <th class="h5 font-weight-bold">配送先</th>
      <td>
        〒<%= @order.post_code %>
        　<%= @order.address %></br>
        <%= @order.name %>
      </td>
    </tr>

    <tr class="row">
      <th class="h5 font-weight-bold">支払い方法</th>
      <td><%= @order.pay_method_i18n %></td>
    </tr>

    <tr class="row">
      <th class="h5 font-weight-bold">注文ステータス</th>
      <td class="pb-4">
        <%= form_with model: @order, url: admin_order_path, method: :patch, local:true do |f| %>
          <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}  %>
          <%= f.submit "更新", class: "btn btn-success ml-3" %>
        <% end %>
    </tr>
  </table>

  <div class="row">
    <table class="table table-hover contents-area col-8 pl-1">
      <thead class="table-active">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_items.each do |order_item| %>
        <tr>
          <td width="30%", class="align-middle"><%= order_item.item.name %></td>
          <td width="20%", class="align-middle"><%= order_item.tax_in_price.to_s(:delimited) %></td>
          <td width="10%", class="align-middle"><%= order_item.quantity %></td>
          <td width="10%", class="align-middle"><%= (order_item.tax_in_price * order_item.quantity).to_s(:delimited) %></td>
          <td width="30%", class="align-middle">
            <%= form_with model: order_item, url: admin_order_item_path(order_item), method: :patch do |f| %>
              <%= f.select :making_status, OrderItem.making_statuses.keys.map {|k| [I18n.t("enums.order_item.making_status.#{k}"), k]} %>
              <%= f.submit "更新", class: "btn btn-success ml-3" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="col-1"></div>

    <table class="table table-hover table-borderless contents-area col-3 h-25 align-self-end justify-content-end">
      <tr>
        <th class="h5 font-weight-bold">商品合計</th>
        <td class="text-right"><%= (@order.billing_amount - @order.postage).to_s(:delimited) %>円</td>
      </tr>

      <tr>
        <th class="h5 font-weight-bold">送料</th>
        <td class="text-right"><%= @order.postage %>円</td>
      </tr>

      <tr>
        <th class="h5 font-weight-bold">請求金額合計</th>
        <td class="text-right font-weight-bold"><%= @order.billing_amount.to_s(:delimited) %>円</td>
      </tr>
    </table>
  </div>
</div>