config/routes.rb
Rails.application.routes.draw do

  # 顧客用ルーティング
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    get '/' => "homes#top", as: "root"
    get 'about' => 'homes#about'

    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdrawal'
      end
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :index, :show, :create] do
      post :confirm, on: :collection
      get :complete, on: :collection
    end

    resources :delivery_addresses, only: [:index, :create, :edit, :update, :destroy]

    get 'search' => 'searches#search'

  end



  # 管理者用ルーティング
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    #homes
    root to: "homes#top"
    #items
    resources :items,only: [:new,:index,:edit,:show,:update,:create]
    #genres
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    #customers
    resources :customers, only: [:index, :show, :edit, :update]
    #orders
    resources :orders, only: [:show, :update, :index]
    #order_items
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container-fluid border-top border-5 mt-auto">
  <div class="text-center pt-3 mt-3">
    <%= link_to "#", class: "text-decoration-none" do %>
      <i class="fas fa-envelope-square h2 text-light"></i>
    <% end %>
    <%= link_to "#", class: "text-decoration-none" do %>
      <i class="fab fa-line h2 text-light"></i>
    <% end %>
    <%= link_to "#", class: "text-decoration-none" do %>
      <i class="fab fa-twitter-square h2 text-light"></i>
    <% end %>
    <%= link_to "#", class: "text-decoration-none" do %>
      <i class="fab fa-instagram-square h2 text-light"></i>
    <% end %>
  </div>
  <p class="text-center text-light">©Nagano-Cake Inc. All Rights reserved.</p>
</div>

<div class="text-center">
  <%= link_to admin_session_path, class: "text-decoration-none text-light h5" do %>
  <i class="fa-solid fa-lock"></i>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg">
    <%= link_to image_tag('logo.png', width: '127', height: '83', class: 'mx-4 my-3'), root_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse">
      <div class="user-name text-dark center-block">
        <% if customer_signed_in? %>
          <p class="pt-3">ようこそ、<span class="h5"><strong><%= current_customer.last_name %><%= current_customer.first_name %></strong></span> 様</p>
        <% elsif admin_signed_in? %>
          <p class="h5 pt-5 pb-5"><strong>管理者ログイン中</strong></p>
        <% else %>
          <p class="pt-3">ようこそ、<span class="h5"><strong>ゲスト</strong></span> 様</p>
        <% end %>
      </div>
        <div class="d-flex flex-column ml-auto">
          <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li class="nav-link px-2">
                <%= link_to admin_items_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
              </li>
              <li class="nav-link px-2">
                <%= link_to admin_customers_path, class: "text-decoration-none text-dark h5" do %>
                  <i class="fas fa-user-check"></i> 会員一覧
                <% end %>
              </li>
              <li class="nav-link px-2">
                <%= link_to admin_orders_path, class: "text-decoration-none text-dark h5" do %>
                  <i class="fas fa-check-square"></i> 注文履歴一覧
                <% end %>
              </li>
              <li class="nav-link px-2">
                <%= link_to admin_genres_path, class: "text-decoration-none text-dark h5" do %>
                  <i class="fas fa-gift"></i>ジャンル一覧
                <% end %>
              </li>
              <li class="nav-link px-2">
                <%= link_to destroy_admin_session_path, method: :delete, class: "text-decoration-none text-dark h5" do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>

        <% elsif customer_signed_in? %>
          <li class="nav-link px-2">
            <%= link_to customer_path(current_customer), class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-user"></i> マイページ
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to items_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to cart_items_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-cart-arrow-down"></i> カート
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to destroy_customer_session_path, method: :delete, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>

        <% else %>
          <li class="nav-link px-2">
            <%= link_to about_path, class: "text-decoration-none text-light text-dark h5" do %>
              <i class="fas fa-heart"></i> About
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to items_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to new_customer_registration_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li class="nav-link px-2">
            <%= link_to customer_session_path, class: "text-decoration-none text-dark h5" do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
          </ul>
          <div class="d-flex flex-row-reverse mt-3">
            <%= render 'public/searches/search' %>
          </div>
        </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano-Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag "favicon-16x16.png" %>
  </head>
<header>
  <%= render 'layouts/header' %>
</header>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</html>